# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'goMoney Football App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for goMoney Football App
pod 'XLPagerTabStrip', '~> 9.0'
pod 'Kingfisher', '~> 7.0'

end
